// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwhbzosonosyrpnxgxku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3aGJ6b3Nvbm9zeXJwbnhneGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDQzNTYsImV4cCI6MjA1ODY4MDM1Nn0.XV6bCwSWBxFP3aYGFcUn4Q2iyDZIAw50z0oLKRQ2nh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);